.mso gproto.tmac
.TH contools_screen 3 2023-12-26
.so contools_screen.3.d/prototypes.3
.rn In_Main_Source 1
.SH NAME
.B
contools_screen
\- Additional screen-oriented console functions
.SH LIBRARY
.PP
link with
.I -lcontools
.\"
.so contools_screen.3.d/synopsis.3
.so contools_screen.3.d/description.3
.so contools_screen.3.d/desc_setup.3
.so contools_screen.3.d/desc_screen.3
.so contools_screen.3.d/desc_styles.3
.so contools_screen.3.d/desc_keypad.3
