.TH contools 3 2023-12-26
.mso gproto.tmac
.so contools.3.d/prototypes.3
.rn In_Main_Source 1
.SH NAME
.B contools
\- Small set of tools to obtain console information
.SH LIBRARY
.PP
link with
.I -lcontools -ltinfo
.\"
.so contools.3.d/synopsis.3
.so contools.3.d/description.3
.so contools.3.d/desc_get_keystroke.3
.so contools.3.d/desc_get_termcap_by_code.3
.so contools.3.d/desc_get_termcap_by_name.3
.so contools.3.d/desc_capname_from_code.3
.so contools.3.d/desc_transforms.3
.so contools.3.d/keys_advice.3
.\"
.SH SEE ALSO
.PP
.BR contools_screen (3)
